# Generated by Django 5.0.2 on 2025-07-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='focus',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', help_text='Language of the content', max_length=10),
        ),
        migrations.AddField(
            model_name='game',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', help_text='Language of the content', max_length=10),
        ),
        migrations.AddField(
            model_name='label',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', help_text='Language of the content', max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', help_text='Language of the content', max_length=10),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch')], default='en', help_text='Language of the content', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='focus',
            unique_together={('name', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('name', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('name', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('name', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingsession',
            unique_together={('name', 'language')},
        ),
    ]
