# Generated by Django 5.0.2 on 2025-07-07 13:02

from django.db import migrations


def populate_language_field(apps, schema_editor):
    """Populate language field with 'en' for all existing records"""
    Focus = apps.get_model('games', 'Focus')
    Material = apps.get_model('games', 'Material')
    Label = apps.get_model('games', 'Label')
    Game = apps.get_model('games', 'Game')
    TrainingSession = apps.get_model('games', 'TrainingSession')
    
    # Update all existing records to have English as the language
    Focus.objects.filter(language__isnull=True).update(language='en')
    Material.objects.filter(language__isnull=True).update(language='en')
    Label.objects.filter(language__isnull=True).update(language='en')
    Game.objects.filter(language__isnull=True).update(language='en')
    TrainingSession.objects.filter(language__isnull=True).update(language='en')


def reverse_populate_language_field(apps, schema_editor):
    """Reverse migration - set language to None (not needed but good practice)"""
    Focus = apps.get_model('games', 'Focus')
    Material = apps.get_model('games', 'Material')
    Label = apps.get_model('games', 'Label')
    Game = apps.get_model('games', 'Game')
    TrainingSession = apps.get_model('games', 'TrainingSession')
    
    # Set language to None for all records (this would be reversed)
    Focus.objects.all().update(language=None)
    Material.objects.all().update(language=None)
    Label.objects.all().update(language=None)
    Game.objects.all().update(language=None)
    TrainingSession.objects.all().update(language=None)


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_focus_language_game_language_label_language_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_language_field, reverse_populate_language_field),
    ]
