# Generated by Django 5.0.2 on 2025-07-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_populate_language_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='focus',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='trainingsession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='focus',
            name='languages',
            field=models.ManyToManyField(related_name='focus_areas', to='games.language'),
        ),
        migrations.AddField(
            model_name='game',
            name='languages',
            field=models.ManyToManyField(related_name='games', to='games.language'),
        ),
        migrations.AddField(
            model_name='label',
            name='languages',
            field=models.ManyToManyField(related_name='labels', to='games.language'),
        ),
        migrations.AddField(
            model_name='material',
            name='languages',
            field=models.ManyToManyField(related_name='materials', to='games.language'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='languages',
            field=models.ManyToManyField(related_name='training_sessions', to='games.language'),
        ),
        migrations.RemoveField(
            model_name='focus',
            name='language',
        ),
        migrations.RemoveField(
            model_name='game',
            name='language',
        ),
        migrations.RemoveField(
            model_name='label',
            name='language',
        ),
        migrations.RemoveField(
            model_name='material',
            name='language',
        ),
        migrations.RemoveField(
            model_name='trainingsession',
            name='language',
        ),
    ]
