# Generated by Django 5.0.2 on 2025-07-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_aboutcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpressumContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the custom section', max_length=200)),
                ('content', models.TextField(help_text='Content in markdown format')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this content should be displayed')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display in the Impressum modal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Impressum Content',
                'verbose_name_plural': 'Impressum Content',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
